apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ehm613abn-python
  janus-idp.io/tekton: ehm613abn-python
  backstage.io/kubernetes-id: ehm613abn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ehm613abn-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
